name: R2RML-RDF-OWLextension

# Tell OntoSpreadEd what sheets to show
sheets:
  - path: sheets/sharkattacks.csv
    kind: entities
    # 'Case Number' exists in your file; use it as the unique key for now.
    # If you later find duplicates, switch to a custom 'id' column you add yourself.
    key: "Case Number"

# Helpful prefixes you’ll likely use later (safe defaults)
prefixes:
  rdf:  "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  owl:  "http://www.w3.org/2002/07/owl#"
  xsd:  "http://www.w3.org/2001/XMLSchema#"
  bfo:  "http://purl.obolibrary.org/obo/BFO_"
  cco:  "http://www.ontologyrepository.com/CommonCoreOntologies/"

# Optional: local or remote ontologies to reference/validate against
external-ontologies:
  - path: ontologies/CommonCoreOntologiesMerged.ttl   # or a URL
  - path: ontologies/bfo.owl

# Optional: where to drop releases/exports if you use the release flow
release:
  out-dir: build/release
